### ISSUE TITLE
I keep getting these error!

### ISSUE THREAD

**Issue by diogoribeirodev** [notsapinho/instagram-profile-downloader#2]
node:fs:1023
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir 'downloads\catswiththeirtonguesout'
    at Object.mkdirSync (node:fs:1023:3)
    at InstagramClient.downloadPostsByUsername (C:\Users\ribei\OneDrive\Documentos\ok\instagram-profile-downloader\dist\classes\InstagramClient.js:35:16)
    at C:\Users\ribei\OneDrive\Documentos\ok\instagram-profile-downloader\dist\index.js:38:22
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'downloads\\catswiththeirtonguesout'
}

**Comment by notsapinho** [comment]
A pasta está sendo criada?

**Comment by diogoribeirodev** [comment]
Sim, ele cria e tbm baixa a foto de perfil

**Comment by notsapinho** [comment]
Tenta rodar o cmd com administrador

**Comment by diogoribeirodev** [comment]
continua a nao funcionar
