### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by horizongfx** [notsapinho/instagram-profile-downloader#3]
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^IGHTS     

IgNotFoundError: GET /api/v1/fbsearch/suggested_searches/?type=users - 404 Not Found; 
    at Request.handleResponseError (E:\instagram-profile-downloader-master\node_modules\instagram-private-api\dist\core\request.js:103:20)
    at Request.send (E:\instagram-profile-downloader-master\node_modules\instagram-private-api\dist\core\request.js:54:28)
    at async FbsearchRepository.suggestedSearches (E:\instagram-profile-downloader-master\node_modules\instagram-private-api\dist\repositories\fbsearch.repository.js:7:26)

**Comment by notsapinho** [comment]
take a look at [#1576](https://github.com/dilame/instagram-private-api/issues/1576) from the instagram private api repo
